### ISSUE TITLE
Progress argument is not returning percent of completion

### ISSUE THREAD

**Issue by paolocorti** [jsonkao/react-scrollama#39]
I'm testing the example on my local machine, when i try to log progress i just see 0 or 1.

**Comment by jsonkao** [comment]
Are you're setting [`progress`](https://github.com/jsonkao/react-scrollama#scrollama) to true?

**Comment by paolocorti** [comment]
I'm using the exact same code of the example. I made a video of the bug, the only way to have progress working is to trigger a resize event
https://youtu.be/EodvbBXFMDs

Downgrading to 2.2.6 seems to solve the problem for me.

**Comment by elbertwang3** [comment]
Just adding that I had the same issue with progress not firing between 0 and 1 with 2.2.7. I downgraded to 2.2.6, and it seems to be working.

Another issue I had with 2.2.7 is that for some reason the first Step was not firing onStepEnter, and every subsequent onStepEnter that fired was off by one. Not sure if the two issues are related at all.

Anyway, I said hi to you at NICAR and thank you for your work on this! :)

**Comment by jsonkao** [comment]
@paolocorti @elbertwang3 thanks for the bug reports. The issue seemed to be the fact that React Scrollama waits until `componentDidMount` to calculate the offset heights of its steps (which the IntersectionObserver root margins are derived from), even though it should actually wait until window load. This is fixed in 4d6a52b3f7d497ceda6a84c3806de46c8e527474.

The upcoming 2.2.8 release should also fix an issue in Chrome where exiting from the top was not being detected if the user scrolled really slowly. For some reason [`topAdjusted`](https://github.com/jsonkao/react-scrollama/blob/master/src/Scrollama.js#L246) takes the floating point value near -0.009375 instead of being > 0. I'm not sure why this happens, probably a weird floating point thing, but [a hacky new condition](https://github.com/jsonkao/react-scrollama/blob/master/src/Scrollama.js#L246) should fix this case.

Also, the changing height of `Step` in the example messes stuff up, I'm looking into that now.

**Comment by jsonkao** [comment]
Ok, this issue is fixed in [2.2.8](https://github.com/jsonkao/react-scrollama/releases/tag/v2.2.8). (Note that if `Step` changes height, progress still [isn't perfect](https://github.com/jsonkao/react-scrollama/issues/39#issuecomment-633689418).)

**Comment by dansundy** [comment]
FYI, I am still experiencing this issue in Safari in `2.2.16`. Rolling back to `2.2.6` works. `2.2.8` does not seem to.

**Comment by jsonkao** [comment]
@dansundy we just released a beta of @maerzhase 's rewrite of the library with functional components.

In your project, can you update React Scrollama to the latest prerelease with `npm i react-scrollama@beta` and see if the error still occurs?

**Comment by dansundy** [comment]
Hi @jsonkao. I will make a reduced test case when I get a chance. It'll likely be a few days before I have the time. Hope that's okay with you.

**Comment by jsonkao** [comment]
No worries!
